# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2025-2026 honeok <i@honeok.com>
# Copyright (c) 2025 zzwsec <zzwsec@163.com>

# References:
# https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml
# https://github.com/Kook-9527/Plugin-backup/blob/main/ClashMeta.yaml
# https://github.com/qichiyuhub/rule/blob/main/config/mihomo/config.yaml
# https://github.com/yyhhyyyyyy/selfproxy/blob/main/Mihomo/mihomo_single.yaml
# https://www.nodeseek.com/post-290031-1
# https://gist.github.com/zhengxiongzhao/097ce20efee1ba0efe3796a1e10e5150

## å…¨å±€é…ç½®
port: 7890 # HTTP(S)ä»£ç†æœåŠ¡å™¨ç«¯å£
socks-port: 7891 # SOCKS5ä»£ç†ç«¯å£
mixed-port: 10801 # HTTP(S)å’ŒSOCKSä»£ç†æ··åˆç«¯å£
redir-port: 7892 # é€æ˜ä»£ç†ç«¯å£, ç”¨äºLinuxå’ŒMacOS

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
tproxy-port: 7893 # Linuxé€æ˜ä»£ç†æœåŠ¡å™¨ç«¯å£

allow-lan: true # å…è®¸å±€åŸŸç½‘è¿æ¥
bind-address: "*" # ç»‘å®šIPåœ°å€, ä»…ä½œç”¨äºallow-lanä¸ºtrue, '*'è¡¨ç¤ºæ‰€æœ‰åœ°å€
skip-auth-prefixes: # è®¾ç½®è·³è¿‡éªŒè¯çš„IPæ®µ
  - 127.0.0.1/8
  - ::1/128
lan-allowed-ips: # å…è®¸è¿æ¥çš„IPåœ°å€æ®µ, ä»…ä½œç”¨äºallow-lanä¸ºtrue, é»˜è®¤å€¼ä¸º0.0.0.0/0å’Œ::/0
  - 0.0.0.0/0
  - ::/0

#  find-process-mode has 3 values: always strict off
#  - always: å¼€å¯, å¼ºåˆ¶åŒ¹é…æ‰€æœ‰è¿›ç¨‹
#  - strict: é»˜è®¤, ç”±mihomoåˆ¤æ–­æ˜¯å¦å¼€å¯
#  - off: ä¸åŒ¹é…è¿›ç¨‹, æ¨èåœ¨è·¯ç”±å™¨ä¸Šä½¿ç”¨æ­¤æ¨¡å¼
find-process-mode: strict

mode: rule

# è‡ªå®šä¹‰ geodata url
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
  asn: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"

geo-auto-update: true # æ˜¯å¦è‡ªåŠ¨æ›´æ–°geodata
geo-update-interval: 24 # æ›´æ–°é—´éš” å•ä½: å°æ—¶

log-level: warning # æ—¥å¿—ç­‰çº§silent/error/warning/info/debug

ipv6: false # IPv6æ€»å¼€å…³, å…³é—­é˜»æ–­æ‰€æœ‰IPv6é“¾æ¥å’Œå±è”½DNSè¯·æ±‚AAAAè®°å½•

unified-delay: true # ç»Ÿä¸€å»¶è¿Ÿæ—¶ä¼šè®¡ç®—RTTä»¥æ¶ˆé™¤è¿æ¥æ¡æ‰‹ç­‰å¸¦æ¥çš„ä¸åŒç±»å‹èŠ‚ç‚¹çš„å»¶è¿Ÿå·®å¼‚

tcp-concurrent: true # TCPå¹¶å‘è¿æ¥æ‰€æœ‰IP, å°†ä½¿ç”¨æœ€å¿«æ¡æ‰‹çš„TCP

# interface-name: en0 # è®¾ç½®å‡ºå£ç½‘å¡

# å…¨å±€TLSæŒ‡çº¹, ä¼˜å…ˆä½äºproxyå†…çš„client-fingerprint
# å¯é€‰ï¼š "chrome" "firefox" "safari" "ios" "random" "none" options.
# Utls is currently support TLS transport in TCP/grpc/WS/HTTP for VLESS/Vmess and trojan.
global-client-fingerprint: firefox

# TCPä¿æŒæ´»åŠ¨é—´éš”
disable-keep-alive: false # ç›®å‰åœ¨androidç«¯å¼ºåˆ¶ä¸ºtrue
keep-alive-idle: 600 # è®¾ç½®TCPè¿æ¥çš„ç©ºé—²è¶…æ—¶æ—¶é—´ä¸º600ç§’

# ç¼“è§£ç§»åŠ¨è®¾å¤‡è€—ç”µé—®é¢˜
# https://github.com/vernesong/OpenClash/issues/2614
keep-alive-interval: 1800 # è®¾ç½®TCPä¿æ´»æ¢æµ‹çš„é—´éš”æ—¶é—´

profile:
  store-selected: true # å­˜å‚¨selecté€‰æ‹©è®°å½•
  store-fake-ip: true # æŒä¹…åŒ–fake-ip

## DNSæ¨¡å—
dns:
  cache-algorithm: arc
  enable: true # å…³é—­å°†ä½¿ç”¨ç³»ç»ŸDNS
  prefer-h3: false # æ˜¯å¦å¼€å¯DoHæ”¯æŒHTTP/3, å°†å¹¶å‘å°è¯•
  listen: :1053 # å¼€å¯DNSæœåŠ¡å™¨ç›‘å¬
  ipv6: false # falseå°†è¿”å›AAAAçš„ç©ºç»“æœ
  # ipv6-timeout: 300 # å•ä½ï¼šms å†…éƒ¨åŒæ ˆå¹¶å‘æ—¶, å‘ä¸Šæ¸¸æŸ¥è¯¢AAAAæ—¶, ç­‰å¾…AAAAçš„æ—¶é—´, é»˜è®¤100ms
  default-nameserver: # æŒ‡å®šåˆå§‹DNSè§£ææœåŠ¡å™¨, ç”¨äºè§£æmihomoè‡ªèº«éœ€è¦çš„åŸŸå (å¦‚è®¢é˜…åœ°å€ã€è§„åˆ™é›†åœ°å€) åªèƒ½ä½¿ç”¨çº¯IPåœ°å€
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip # å¯ç”¨Fake-IPæ¨¡å¼ or redir-host

  fake-ip-range: 198.18.0.1/16 # fake-ipæ± è®¾ç½®
  # fake-ip-range6: fdfe:dcba:9876::1/64 # fake-ip6æ± è®¾ç½®

  # é…ç½®ä¸ä½¿ç”¨fake-ipçš„åŸŸå
  fake-ip-filter:
    - rule-set:fakeipfilter_domain
  fake-ip-filter-mode: blacklist # é…ç½®fake-ip-filterçš„åŒ¹é…æ¨¡å¼, é»˜è®¤ä¸ºblacklist, å³å¦‚æœåŒ¹é…æˆåŠŸä¸è¿”å›fake-ip

  # use-hosts: true # æŸ¥è¯¢hosts

  # é…ç½®åé¢çš„nameserver fallbackå’Œnameserver-policyå‘dnsæœåŠ¡å™¨çš„è¿æ¥è¿‡ç¨‹æ˜¯å¦éµå®ˆéµå®ˆrulesè§„åˆ™
  # å¦‚æœä¸ºfalse(é»˜è®¤å€¼) åˆ™è¿™ä¸‰éƒ¨åˆ†çš„dnsæœåŠ¡å™¨åœ¨æœªç‰¹åˆ«æŒ‡å®šçš„æƒ…å†µä¸‹ä¼šç›´è¿
  # å¦‚æœä¸ºtrue, å°†ä¼šæŒ‰ç…§rulesçš„è§„åˆ™åŒ¹é…é“¾æ¥æ–¹å¼ (èµ°ä»£ç†æˆ–ç›´è¿), å¦‚æœæœ‰ç‰¹åˆ«æŒ‡å®šåˆ™ä»»ç„¶ä»¥æŒ‡å®šå€¼ä¸ºå‡†
  # ä»…å½“proxy-server-nameserveréç©ºæ—¶å¯ä»¥å¼€å¯æ­¤é€‰é¡¹, å¼ºçƒˆä¸å»ºè®®å’Œprefer-h3ä¸€èµ·ä½¿ç”¨
  # æ­¤å¤–, è¿™ä¸‰è€…é…ç½®ä¸­çš„dnsæœåŠ¡å™¨å¦‚æœå‡ºç°åŸŸåä¼šé‡‡ç”¨default-nameserveré…ç½®é¡¹è§£æ, ä¹Ÿè¯·ç¡®ä¿æ­£ç¡®é…ç½®default-nameserver
  respect-rules: true

  # DNSä¸»è¦åŸŸåé…ç½®
  # æ”¯æŒUDP TCP DoT DoH DoQ
  # è¿™éƒ¨åˆ†ä¸ºä¸»è¦DNSé…ç½®, å½±å“æ‰€æœ‰ç›´è¿, ç¡®ä¿ä½¿ç”¨å¯¹å¤§é™†è§£æç²¾å‡†çš„DNS
  nameserver:
    - https://one.one.one.one/dns-query
    - https://dns.google/dns-query

  # ä¸“ç”¨äºèŠ‚ç‚¹åŸŸåè§£æçš„DNSæœåŠ¡å™¨, éå¿…è¦é…ç½®é¡¹, å¦‚æœä¸å¡«åˆ™éµå¾ªnameserver-policy nameserverå’Œfallbackçš„é…ç½®
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  # é…ç½®æŸ¥è¯¢åŸŸåä½¿ç”¨çš„DNSæœåŠ¡å™¨
  nameserver-policy:
    "rule-set:private_domain,cn_domain,direct_domain":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:category-ads-all": rcode://success # å¹¿å‘ŠåŸŸååœ¨DNSå±‚ç›´æ¥è¿”å›"æˆåŠŸä½†æ— è®°å½•"

## èŠ‚ç‚¹ä¿¡æ¯
proxies:
  # é“¾å¼ä»£ç†æµé‡èµ°å‘æœºåˆ¶ ä¸¨ Mihomoæœ¬æœº <-> å‰ç½®èŠ‚ç‚¹ <-> è½åœ°èŠ‚ç‚¹ <-> Internetäº’è”ç½‘
  - name: "ğŸ‡¸ğŸ‡¬ ç‹®åŸé“¾å¼"
    dialer-proxy: "ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨"
    type: socks5
    server: "1.1.1.1"
    port: 1080
    username: "socks"
    password: "socks"

  # Shadowsocks
  # cipheræ”¯æŒ:
  # aes-128-gcm aes-192-gcm aes-256-gcm
  # aes-128-cfb aes-192-cfb aes-256-cfb
  # aes-128-ctr aes-192-ctr aes-256-ctr
  # rc4-md5 chacha20-ietf xchacha20
  # chacha20-ietf-poly1305 xchacha20-ietf-poly1305
  # 2022-blake3-aes-128-gcm 2022-blake3-aes-256-gcm 2022-blake3-chacha20-poly1305
  - name: "ğŸ‡­ğŸ‡° é¦™æ¸¯é“¾å¼"
    dialer-proxy: "ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨"
    type: ss
    server: "1.0.0.1"
    port: 8388
    cipher: "aes-128-gcm"
    password: "shadowsocks"

## æœºåœºé€šç”¨é…ç½®æ¨¡æ¿
airport_conf: &airport_conf
  type: http
  interval: 3600 # è‡ªåŠ¨æ›´æ–°æ—¶é—´(ç§’)
  proxy: DIRECT # é€šè¿‡ç›´è¿æ‹‰å–æœºåœºè®¢é˜…, è¯¥åå­—æ˜¯æŒ‡ç­–ç•¥ç»„æˆ–æŸä¸ªä»£ç†èŠ‚ç‚¹çš„åå­—
  lazy: true # æ‡’åŠ è½½
  health-check: # èŠ‚ç‚¹è‡ªåŠ¨æ£€æµ‹å»¶æ—¶
    enable: true
    interval: 300
    url: "http://connectivitycheck.gstatic.com/generate_204"
    expected-status: 204 # å½“å¥åº·æ£€æŸ¥è¿”å›çŠ¶æ€ç ä¸æœŸæœ›å€¼ä¸ç¬¦æ—¶è®¤ä¸ºèŠ‚ç‚¹ä¸å¯ç”¨

# ç­–ç•¥ç»„å¼•ç”¨åˆ—è¡¨
Airports: &airports
  use:
    - Airport1
    - Airport2

# æœºåœºè®¢é˜…åˆé›†
proxy-providers:
  Airport1:
    <<: *airport_conf
    url: "url1"
  Airport2:
    <<: *airport_conf
    url: "url2"

## ä»£ç†åˆ†ç»„é”šç‚¹
main: &main { type: select, include-all: true, proxies: [ğŸš€ é»˜è®¤ä»£ç†, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ‡³ğŸ‡± è·å…°è‡ªåŠ¨, ğŸ‡©ğŸ‡ª å¾·å›½è‡ªåŠ¨, DIRECT] }
proxy: &proxy { type: select, include-all: true, proxies: [ğŸš€ é»˜è®¤ä»£ç†, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ‡³ğŸ‡± è·å…°è‡ªåŠ¨, ğŸ‡©ğŸ‡ª å¾·å›½è‡ªåŠ¨] }
specific: &specific { type: select, include-all: true, <<: *airports, filter: "^((?!(?i)(ğŸ‡­ğŸ‡°|é¦™æ¸¯|hk|hong\\s?kong|ğŸ‡²ğŸ‡´|æ¾³é—¨|æ¾³é–€|macau|macao|ğŸ‡·ğŸ‡º|ä¿„ç½—æ–¯|ru|russia|ğŸ‡¨ğŸ‡³|ä¸­å›½|å›å›½|china|cn)).)*$" }
island: &island { type: select, proxies: [DIRECT], <<: *airports, filter: "(?i)(ğŸ‡­ğŸ‡°|é¦™æ¸¯|hk|hong\\s?kong|ğŸ‡²ğŸ‡´|æ¾³é—¨|æ¾³é–€|macau|macao|ğŸ‡¹ğŸ‡¼|å°æ¹¾|å°ç£|tw|taiwan|taipei)" }

## ä»£ç†åˆ†ç»„
proxy-groups:
  #------------------------åŸºç¡€åˆ†ç»„------------------------#
  - { name: ğŸš€ é»˜è®¤ä»£ç†, type: select, include-all: true, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, ğŸ‡³ğŸ‡± è·å…°è‡ªåŠ¨, ğŸ‡©ğŸ‡ª å¾·å›½è‡ªåŠ¨] }
  - { name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 100, url: "http://connectivitycheck.gstatic.com/generate_204", interval: 300 }

  #------------------------åœºæ™¯åˆ†ç»„------------------------#
  - { name: ğŸ¤– AI, <<: *specific }
  - { name: ğŸ€ Google, <<: *proxy }
  - { name: ğŸ‘¨â€ğŸ’» GitHub, <<: *proxy }
  - { name: ğŸ¦Š GitLab, <<: *proxy }
  - { name: ğŸ³ Docker, <<: *proxy }
  - { name: ğŸªŸ Microsoft, <<: *main }
  - { name: ğŸ¬ OneDrive, <<: *main }
  - { name: ğŸ“² Telegram, <<: *proxy }
  - { name: ğŸ“º BiliBili, <<: *island }
  - { name: ğŸ¥ NETFLIX, <<: *specific }
  - { name: ğŸ§ Spotify, <<: *island }
  - { name: ğŸµ TikTok, <<: *specific }
  - { name: ğŸ’¶ PayPal, <<: *main }
  - { name: âœˆï¸ Speedtest, <<: *main }
  - { name: ğŸ Apple, <<: *main }

  #------------------------åœ°åŒºåˆ†ç»„------------------------#
  - { name: ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, type: url-test, <<: *airports, include-all: true, tolerance: 100, filter: "(?i)(ğŸ‡­ğŸ‡°|é¦™æ¸¯|hk|hong\\s?kong)", url: "http://connectivitycheck.gstatic.com/generate_204", interval: 300 }
  - { name: ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, type: url-test, <<: *airports, include-all: true, tolerance: 100, filter: "(?i)(ğŸ‡¹ğŸ‡¼|å°æ¹¾|tw|taiwan|taipei)", url: "http://connectivitycheck.gstatic.com/generate_204", interval: 300 }
  - { name: ğŸ‡¸ğŸ‡¬ ç‹®åŸè‡ªåŠ¨, type: url-test, <<: *airports, include-all: true, tolerance: 100, filter: "(?i)(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|sg|singapore|lion\\s?city)", url: "http://connectivitycheck.gstatic.com/generate_204", interval: 300 }
  - { name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, type: url-test, <<: *airports, include-all: true, tolerance: 100, filter: "(?i)(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|jp|japan|tokyo|osaka)", url: "http://connectivitycheck.gstatic.com/generate_204", interval: 300 }
  - { name: ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, type: url-test, <<: *airports, include-all: true, tolerance: 100, filter: "(?i)(ğŸ‡ºğŸ‡¸|ç¾å›½|us|united\\s?states|america)", url: "http://connectivitycheck.gstatic.com/generate_204", interval: 300 }
  - { name: ğŸ‡³ğŸ‡± è·å…°è‡ªåŠ¨, type: url-test, <<: *airports, include-all: true, tolerance: 100, filter: "(?i)(ğŸ‡³ğŸ‡±|è·å…°|nl|netherlands|amsterdam)", url: "http://connectivitycheck.gstatic.com/generate_204", interval: 300 }
  - { name: ğŸ‡©ğŸ‡ª å¾·å›½è‡ªåŠ¨, type: url-test, <<: *airports, include-all: true, tolerance: 100, filter: "(?i)(ğŸ‡©ğŸ‡ª|å¾·å›½|de|germany|frankfurt)", url: "http://connectivitycheck.gstatic.com/generate_204", interval: 300 }

  #------------------------ç‰¹æ®Šåˆ†ç»„------------------------#
  - { name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT, ğŸš€ é»˜è®¤ä»£ç†] }
  - { name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *main }

## è§„åˆ™åŒ¹é…
rules:
  # æœ¬åœ°å±€åŸŸç½‘
  - RULE-SET,private_ip,DIRECT,no-resolve
  - RULE-SET,private_domain,DIRECT

  # å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,awaAd_domain,REJECT

  # åº”ç”¨åˆ†æµ
  - RULE-SET,meituan_domain,DIRECT
  - RULE-SET,appleCn_domain,DIRECT

  - RULE-SET,apple_domain,ğŸ Apple
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,ai_domain,ğŸ¤– AI
  - RULE-SET,github_domain,ğŸ‘¨â€ğŸ’» GitHub
  - RULE-SET,gitlab_domain,ğŸ¦Š GitLab
  - RULE-SET,docker_domain, ğŸ³ Docker
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,onedrive_domain,ğŸ¬ OneDrive
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,bilibili_domain,ğŸ“º BiliBili
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,spotify_domain,ğŸ§ Spotify
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,speedtest_domain,âœˆï¸ Speedtest

  - RULE-SET,cn_ip,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,cn_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,direct_domain,DIRECT
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†

  - RULE-SET,google_ip,ğŸ€ Google,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve

  # å…œåº•è§„åˆ™
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

## è§„åˆ™é›†
# https://github.com/MetaCubeX/meta-rules-dat
rule-anchor:
  class: &class { type: http, interval: 86400, behavior: classical, format: text }
  domain: &domain { type: http, interval: 86400, behavior: domain, format: mrs }
  ip: &ip { type: http, interval: 86400, behavior: ipcidr, format: mrs }

## è§„åˆ™
rule-providers:
  # å¹¿å‘Šè§„åˆ™
  awaAd_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/TG-Twilight/AWAvenue-Ads-Rule@main/Filters/AWAvenue-Ads-Rule-Clash.mrs" }

  ai_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ai-!cn.mrs" }
  apple_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple.mrs" }
  appleCn_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple-cn.mrs" }
  bilibili_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/bilibili.mrs" }
  cn_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs" }
  direct_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/wwqgtxx/clash-rules@release/direct.mrs" }
  docker_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/docker.mrs" }
  fakeipfilter_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/wwqgtxx/clash-rules@release/fakeip-filter.mrs" }
  geolocation-!cn: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.mrs" }
  github_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/github.mrs" }
  gitlab_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/gitlab.mrs" }
  google_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs" }
  meituan_domain: { <<: *class, url: "https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Shadowrocket/MeiTuan/MeiTuan.list" }
  microsoft_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs" }
  netflix_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/netflix.mrs" }
  onedrive_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/onedrive.mrs" }
  paypal_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/paypal.mrs" }
  private_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs" }
  speedtest_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/speedtest.mrs" }
  spotify_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.mrs" }
  telegram_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs" }
  tiktok_domain: { <<: *domain, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tiktok.mrs" }

  cn_ip: { <<: *ip, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs" }
  google_ip: { <<: *ip, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/google.mrs" }
  netflix_ip: { <<: *ip, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/netflix.mrs" }
  private_ip: { <<: *ip, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs" }
  telegram_ip: { <<: *ip, url: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/telegram.mrs" }
