---
name: "Build Mihomo"

on:
  push:
    branches: [master, release]
    paths:
      - "core/mihomo/**"
      - "!core/mihomo/**/*.md"
      - ".github/workflows/mihomo.yaml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "core/mihomo/**"
      - "!core/mihomo/**/*.md"
      - ".github/workflows/mihomo.yaml"
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WORK_DIR: core/mihomo
  DOCKERHUB_REPO: ${{ secrets.DOCKER_USERNAME || github.repository_owner }}/mihomo

jobs:
  check:
    name: "Pre check"
    runs-on: ubuntu-latest
    outputs:
      renew: ${{ steps.vers.outputs.renew }}
      mihomo_version: ${{ steps.vers.outputs.mihomo_version }}

    steps:
      - name: "Fetch Versions and Decide"
        id: vers
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -eEuxo pipefail
          RENEW="false"
          LATEST_VER="$(gh release view -R MetaCubeX/mihomo --json tagName -q .tagName)"
          CURRENT_VER="$(skopeo list-tags "docker://docker.io/$DOCKERHUB_REPO" 2>/dev/null | jq -r '.Tags[] | select(test("^v"))' | sort -rV | head -n 1 || true)"
          if [[ "$(printf '%s\n%s\n' "$LATEST_VER" "$CURRENT_VER" | sort -V | head -n 1)" != "$LATEST_VER" ]] || [[ -z "$CURRENT_VER" && -n "$LATEST_VER" ]]; then
            echo "Build required."
            RENEW="true"
          fi
          echo "renew=${RENEW}" >> "$GITHUB_OUTPUT"
          echo "mihomo_version=${LATEST_VER}" >> "$GITHUB_OUTPUT"

  build:
    name: "Build image"
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.renew == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/386
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Prepare"
        run: |
          PLATFORM_PAIR=$(awk -F/ '{print $1"-"$2$3}' <<< ${{ matrix.platform }})
          echo "PLATFORM_PAIR=$PLATFORM_PAIR" >> "$GITHUB_ENV"

      - name: "Download geodat"
        working-directory: ${{ env.WORK_DIR }}
        run: |
          set -eEuxo pipefail
          curl -L -O https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
          curl -L -O https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
          curl -L -O https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
          curl -L -O https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=${{ needs.check.outputs.mihomo_version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description=Mihomo is a high-performance, cross-platform rule-based tunnel core supporting modern protocols like VLESS, Hysteria2, and TUIC.
            org.opencontainers.image.source=https://github.com/MetaCubeX/mihomo
            org.opencontainers.image.title=mihomo
            org.opencontainers.image.url=https://wiki.metacubex.one

      - name: "Build and export"
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORK_DIR }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: MIHOMO_VERSION=${{ needs.check.outputs.mihomo_version }}
          outputs: >
            type=image,
            name=${{ env.DOCKERHUB_REPO }},
            push-by-digest=${{ github.ref_name == github.event.repository.default_branch }},
            name-canonical=${{ github.ref_name == github.event.repository.default_branch }},
            push=${{ github.ref_name == github.event.repository.default_branch }}

      - name: "Export digest"
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        run: |
          rm -rf /tmp/digests
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: "Upload artifact"
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        uses: actions/upload-artifact@v6
        with:
          name: digest-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    name: "Merge manifest"
    needs: [check, build]
    if: ${{ github.ref_name == github.event.repository.default_branch }}

    steps:
      - name: "Download digests"
        uses: actions/download-artifact@v7
        with:
          path: /tmp/digests
          pattern: digest-*
          merge-multiple: true

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=${{ needs.check.outputs.mihomo_version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description=Mihomo is a high-performance, cross-platform rule-based tunnel core supporting modern protocols like VLESS, Hysteria2, and TUIC.
            org.opencontainers.image.source=https://github.com/MetaCubeX/mihomo
            org.opencontainers.image.title=mihomo
            org.opencontainers.image.url=https://wiki.metacubex.one

      - name: "Create manifest list and push"
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)

      - name: "Inspect image"
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ needs.check.outputs.mihomo_version }}
