---
name: "Build Xray"

on:
  push:
    branches: [master, release]
    paths:
      - "core/xray/**"
      - "!core/xray/**/*.md"
      - ".github/workflows/xray.yaml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "core/xray/**"
      - "!core/xray/**/*.md"
      - ".github/workflows/xray.yaml"
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_REPO: ${{ secrets.DOCKER_USERNAME || github.repository_owner }}/xray

jobs:
  check:
    name: "Pre check"
    runs-on: ubuntu-latest
    outputs:
      renew: ${{ steps.vers.outputs.renew }}
      xray_tag: ${{ steps.vers.outputs.xray_tag }}
      xray_version: ${{ steps.vers.outputs.xray_version }}

    steps:
      - name: "Fetch Versions and Decide"
        id: vers
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -eEuxo pipefail
          RENEW="false"
          LATEST_TAG="$(gh release view -R XTLS/Xray-core --json tagName -q .tagName)"
          LATEST_VER=${LATEST_TAG#v}
          CURRENT_VER="$(skopeo list-tags "docker://docker.io/$DOCKERHUB_REPO" 2>/dev/null | jq -r '.Tags[] | select(. != "latest")' | sort -rV | head -n1 || true)"
          if [[ "$(printf '%s\n%s\n' "$LATEST_VER" "$CURRENT_VER" | sort -V | head -n1)" != "$LATEST_VER" ]] || [[ -z "$CURRENT_VER" && -n "$LATEST_VER" ]]; then
            echo "Build required."
            RENEW="true"
          fi
          echo "renew=${RENEW}" >> "$GITHUB_OUTPUT"
          echo "xray_tag=${LATEST_TAG}" >> "$GITHUB_OUTPUT"
          echo "xray_version=${LATEST_VER}" >> "$GITHUB_OUTPUT"

  release:
    name: "Build binary"
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.renew == 'true' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: true
      matrix:
        include:
          - { goos: linux, goarch: "386", platform: "linux/386" }
          - { goos: linux, goarch: amd64, platform: "linux/amd64" }
          - { goos: linux, goarch: arm, goarm: "6", platform: "linux/arm/v6" }
          - { goos: linux, goarch: arm, goarm: "7", platform: "linux/arm/v7" }
          - { goos: linux, goarch: arm64, platform: "linux/arm64" }
          - { goos: linux, goarch: ppc64le, platform: "linux/ppc64le" }
          - { goos: linux, goarch: riscv64, platform: "linux/riscv64" }
          - { goos: linux, goarch: s390x, platform: "linux/s390x" }
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Clone source code"
        working-directory: core/xray
        run: git clone --depth=1 --branch ${{ needs.check.outputs.xray_tag }} https://github.com/XTLS/Xray-core.git src

      - name: "Setup Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: core/xray/src/go.mod
          check-latest: true
          cache-dependency-path: core/xray/src/go.sum

      - name: "Download gomod"
        working-directory: core/xray/src
        run: go mod download

      - name: "Build Xray-core"
        working-directory: core/xray/src
        run: |
          set -eEuxo pipefail
          COMMID="$(git rev-parse --short HEAD)"

          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM"
          go build -v -trimpath -o xray -buildvcs=false -gcflags="all=-l=4" \
          -ldflags="-X github.com/xtls/xray-core/core.build=${COMMID} -s -w -buildid=" \
          ./main

      - name: "Prepare assets"
        working-directory: core/xray/src
        run: |
          set -eEuxo pipefail
          PLATFORM_PAIR=$(awk -F/ '{print $1"-"$2$3}' <<< "${{ matrix.platform }}")
          echo "PLATFORM_PAIR=$PLATFORM_PAIR" >> "$GITHUB_ENV"
          BINARY_NAME="xray-$GOARCH"
          if [ -n "$GOARM" ]; then
            BINARY_NAME="${BINARY_NAME}v${GOARM}"
          fi
          mv xray "$BINARY_NAME"
          echo "BINARY_NAME=${BINARY_NAME}" >> "$GITHUB_ENV"

      - name: "Upload artifact"
        uses: actions/upload-artifact@v6
        with:
          name: xray-${{ env.PLATFORM_PAIR }}
          path: core/xray/src/${{ env.BINARY_NAME }}
          if-no-files-found: error
          retention-days: 1

  build:
    name: "Build image"
    runs-on: ubuntu-latest
    needs: [check, release]
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/386
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/riscv64
          - linux/s390x

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Prepare"
        run: |
          PLATFORM_PAIR=$(awk -F/ '{print $1"-"$2$3}' <<< "${{ matrix.platform }}")
          echo "PLATFORM_PAIR=$PLATFORM_PAIR" >> "$GITHUB_ENV"

      - name: "Download binary"
        uses: actions/download-artifact@v7
        with:
          name: xray-${{ env.PLATFORM_PAIR }}
          path: core/xray

      - name: "Download geodat"
        working-directory: core/xray
        run: |
          set -eEuxo pipefail
          declare -a GEO_FILES=("geoip" "geosite")
          for GEO_FILE in "${GEO_FILES[@]}"; do
            curl -L -O "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/$GEO_FILE.dat"
            curl -L -O "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/$GEO_FILE.dat.sha256sum"
            sha256sum -c "$GEO_FILE.dat.sha256sum"
          done

      - name: "Prepare binary"
        working-directory: core/xray
        run: |
          ls -la xray-*
          chmod +x xray-*

      - name: "Setup Docker QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Extract Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=${{ needs.check.outputs.xray_version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description=Xray, Penetrates Everything. Also the best v2ray-core. Where the magic happens. An open platform for various uses.
            org.opencontainers.image.source=https://github.com/XTLS/Xray-core
            org.opencontainers.image.title=Xray
            org.opencontainers.image.url=https://xtls.github.io

      - name: "Build and export"
        id: build
        uses: docker/build-push-action@v6
        with:
          context: core/xray/
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: >
            type=image,
            name=${{ env.DOCKERHUB_REPO }},
            push-by-digest=${{ github.ref_name == github.event.repository.default_branch }},
            name-canonical=${{ github.ref_name == github.event.repository.default_branch }},
            push=${{ github.ref_name == github.event.repository.default_branch }}

      - name: "Export digest"
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        run: |
          rm -rf /tmp/digests
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: "Upload artifact"
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        uses: actions/upload-artifact@v6
        with:
          name: digest-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    name: "Merge manifest"
    needs: [check, build]
    if: ${{ github.ref_name == github.event.repository.default_branch }}

    steps:
      - name: "Download digests"
        uses: actions/download-artifact@v7
        with:
          path: /tmp/digests
          pattern: digest-*
          merge-multiple: true

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Extract Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=raw,value=${{ needs.check.outputs.xray_version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description=Xray, Penetrates Everything. Also the best v2ray-core. Where the magic happens. An open platform for various uses.
            org.opencontainers.image.source=https://github.com/XTLS/Xray-core
            org.opencontainers.image.title=Xray
            org.opencontainers.image.url=https://xtls.github.io

      - name: "Create manifest list and push"
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)

      - name: "Inspect image"
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ needs.check.outputs.xray_version }}

  sync:
    name: "Sync readme"
    runs-on: ubuntu-latest
    needs: [merge]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Sync readme to dockerhub"
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKERHUB_REPO }}
          readme-filepath: core/xray/README.md
          enable-url-completion: false
